package com.desktop.app.filebrowser.main;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author raghu
 */

import java.awt.Color;
import java.awt.EventQueue;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.LayoutStyle.ComponentPlacement;

import com.desktop.app.filebrowser.bean.Users;
import com.desktop.app.filebrowser.helper.StoreFileAsJson;
import com.microsoft.sqlserver.jdbc.StringUtils;

public class RegisterForm extends javax.swing.JFrame {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private static final Logger LOGGER = Logger.getLogger(RegisterForm.class
			.getName());
	private static final String FONT_LABEL = "Tahoma";

	/**
	 * Creates new form RegisterForm
	 */
	public RegisterForm() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	private void initComponents() {

		// Variables declaration - do not modify//GEN-BEGIN:variables
		javax.swing.JButton jButton2;
		javax.swing.JButton jButtonRegister;
		javax.swing.JLabel jLabel10;
		javax.swing.JLabel jLabel2;
		javax.swing.JLabel jLabel4;
		javax.swing.JLabel jLabel5;
		javax.swing.JLabel jLabel6;
		javax.swing.JLabel jLabel7;
		javax.swing.JLabel jLabel8;
		javax.swing.JLabel jLabelClose;
		javax.swing.JLabel jLabelMin;
		javax.swing.JLabel jLabelRegister;
		javax.swing.JPanel jPanel1;
		javax.swing.JPanel jPanel2;
		javax.swing.JTextArea jTextArea1;

		jPanel1 = new javax.swing.JPanel();
		jLabelClose = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabelMin = new javax.swing.JLabel();
		jPanel2 = new javax.swing.JPanel();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jTextField1 = new javax.swing.JTextField();
		jPasswordField1 = new javax.swing.JPasswordField();
		jButtonRegister = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jLabel6 = new javax.swing.JLabel();
		jTextField2 = new javax.swing.JTextField();
		jLabel7 = new javax.swing.JLabel();
		jTextField3 = new javax.swing.JTextField();
		jLabel8 = new javax.swing.JLabel();
		jPasswordField2 = new javax.swing.JPasswordField();
		jLabel10 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setUndecorated(true);

		jPanel1.setBackground(new java.awt.Color(248, 148, 6));

		jLabelClose.setFont(new java.awt.Font(FONT_LABEL, 1, 24)); // NOI18N
		jLabelClose.setForeground(new java.awt.Color(255, 255, 255));
		jLabelClose.setText("X");
		jLabelClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
		jLabelClose.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent evt) {
				System.exit(0);
			}
		});

		jLabel2.setFont(new java.awt.Font(FONT_LABEL, 1, 24)); // NOI18N
		jLabel2.setForeground(new java.awt.Color(255, 255, 255));
		jLabel2.setText("Register");

		jLabelMin.setFont(new java.awt.Font(FONT_LABEL, 1, 24)); // NOI18N
		jLabelMin.setForeground(new java.awt.Color(255, 255, 255));
		jLabelMin.setText("-");
		jLabelMin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
		jLabelMin.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent evt) {
				setState(JFrame.ICONIFIED);
			}
		});
		jLabelRegister = new javax.swing.JLabel();

		jLabelRegister.setFont(new java.awt.Font(FONT_LABEL, 0, 14)); // NOI18N
		jLabelRegister.setForeground(new Color(0, 0, 0));
		jLabelRegister.setText("click here to login");
		jLabelRegister.setCursor(new java.awt.Cursor(
				java.awt.Cursor.HAND_CURSOR));
		jLabelRegister.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent evt) {
				
				LoginForm lgf = new LoginForm();
				lgf.setVisible(true);
				
	            lgf.setIconImages(LoginForm.getImages());
				lgf.pack();
				lgf.setLocationRelativeTo(null);
				lgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
				dispose();
			}
		});

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(
				Alignment.TRAILING).addGroup(
				jPanel1Layout
						.createSequentialGroup()
						.addGap(29)
						.addComponent(jLabel2)
						.addPreferredGap(ComponentPlacement.RELATED, 211,
								Short.MAX_VALUE).addComponent(jLabelRegister)
						.addGap(18).addComponent(jLabelMin).addGap(18)
						.addComponent(jLabelClose).addGap(21)));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																Alignment.LEADING)
														.addGroup(
																jPanel1Layout
																		.createParallelGroup(
																				Alignment.BASELINE)
																		.addComponent(
																				jLabelMin,
																				GroupLayout.DEFAULT_SIZE,
																				38,
																				Short.MAX_VALUE)
																		.addComponent(
																				jLabelClose)
																		.addComponent(
																				jLabelRegister))
														.addComponent(
																jLabel2,
																GroupLayout.DEFAULT_SIZE,
																38,
																Short.MAX_VALUE))
										.addContainerGap()));
		jPanel1.setLayout(jPanel1Layout);

		jPanel2.setBackground(new Color(204, 204, 204));

		jLabel4.setFont(new java.awt.Font(FONT_LABEL, 0, 18)); // NOI18N
		jLabel4.setForeground(new Color(51, 51, 51));
		jLabel4.setText("Email-Id:");

		jLabel5.setFont(new java.awt.Font(FONT_LABEL, 0, 18)); // NOI18N
		jLabel5.setForeground(new Color(51, 51, 51));
		jLabel5.setText("Password:");

		jTextField1.setBackground(new Color(255, 255, 255));
		jTextField1.setFont(new java.awt.Font(FONT_LABEL, 0, 14)); // NOI18N
		jTextField1.setForeground(new Color(0, 0, 0));

		jPasswordField1.setBackground(new Color(255, 255, 255));
		jPasswordField1.setFont(new java.awt.Font(FONT_LABEL, 0, 14)); // NOI18N
		jPasswordField1.setForeground(new Color(0, 0, 0));

		jButtonRegister.setBackground(new java.awt.Color(34, 167, 240));
		jButtonRegister.setFont(new java.awt.Font(FONT_LABEL, 1, 14)); // NOI18N
		jButtonRegister.setForeground(new java.awt.Color(255, 255, 255));
		jButtonRegister.setText("Register");
		jButtonRegister
				.addActionListener(evt -> jButtonRegisterActionPerformed());

		jButton2.setBackground(new java.awt.Color(242, 38, 19));
		jButton2.setFont(new java.awt.Font(FONT_LABEL, 1, 14)); // NOI18N
		jButton2.setForeground(new java.awt.Color(255, 255, 255));
		jButton2.setText("Cancel");
		jButton2
		.addActionListener(evt->System.exit(0));

		jLabel6.setFont(new java.awt.Font(FONT_LABEL, 0, 18)); // NOI18N
		jLabel6.setForeground(new Color(51, 51, 51));
		jLabel6.setText("User Name:");

		jTextField2.setBackground(new Color(255, 255, 255));
		jTextField2.setFont(new java.awt.Font(FONT_LABEL, 0, 14)); // NOI18N
		jTextField2.setForeground(new Color(0, 0, 0));

		jLabel7.setFont(new java.awt.Font(FONT_LABEL, 0, 18)); // NOI18N
		jLabel7.setForeground(new Color(51, 51, 51));
		jLabel7.setText("     Display Name:");

		jTextField3.setBackground(new Color(255, 255, 255));
		jTextField3.setFont(new java.awt.Font(FONT_LABEL, 0, 14)); // NOI18N
		jTextField3.setForeground(new Color(0, 0, 0));

		jLabel8.setFont(new java.awt.Font(FONT_LABEL, 0, 18)); // NOI18N
		jLabel8.setForeground(new Color(51, 51, 51));
		jLabel8.setText("Retype Pass:");

		jPasswordField2.setBackground(new Color(255, 255, 255));
		jPasswordField2.setFont(new java.awt.Font(FONT_LABEL, 0, 14)); // NOI18N
		jPasswordField2.setForeground(new Color(0, 0, 0));

		jLabel10.setFont(new java.awt.Font(FONT_LABEL, 0, 18)); // NOI18N
		jLabel10.setForeground(new Color(51, 51, 51));
		jLabel10.setText("Address:");

		firstNameValidation = new JLabel();
		firstNameValidation.setForeground(new Color(204, 51, 51));
		firstNameValidation.setBorder(null);
		firstNameValidation.setBackground(new Color(204, 204, 204));

		lastNameValidation = new JLabel();
		lastNameValidation.setForeground(new Color(204, 51, 51));
		lastNameValidation.setBorder(null);
		lastNameValidation.setBackground(new Color(204, 204, 204));

		emailIdValidation = new JLabel("");
		emailIdValidation.setForeground(new Color(204, 51, 51));
		emailIdValidation.setBorder(null);
		emailIdValidation.setBackground(new Color(204, 204, 204));

		passWordValidation = new JLabel();
		passWordValidation.setForeground(new Color(204, 51, 51));
		passWordValidation.setBorder(null);
		passWordValidation.setBackground(new Color(204, 204, 204));

		retypeValidation = new JLabel();
		retypeValidation.setForeground(new Color(204, 51, 51));
		retypeValidation.setBorder(null);
		retypeValidation.setBackground(new Color(204, 204, 204));
		jTextArea1 = new javax.swing.JTextArea();

		jTextArea1.setBackground(new Color(255, 255, 255));
		jTextArea1.setColumns(20);
		jTextArea1.setForeground(new Color(0, 0, 0));
		jTextArea1.setRows(5);

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(
				jPanel2);
		jPanel2Layout
				.setHorizontalGroup(jPanel2Layout
						.createParallelGroup(Alignment.TRAILING)
						.addGroup(
								jPanel2Layout
										.createSequentialGroup()
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																Alignment.TRAILING)
														.addGroup(
																jPanel2Layout
																		.createSequentialGroup()
																		.addGap(43)
																		.addGroup(
																				jPanel2Layout
																						.createParallelGroup(
																								Alignment.TRAILING)
																						.addGroup(
																								jPanel2Layout
																										.createParallelGroup(
																												Alignment.LEADING)
																										.addGroup(
																												jPanel2Layout
																														.createSequentialGroup()
																														.addPreferredGap(
																																ComponentPlacement.RELATED,
																																51,
																																Short.MAX_VALUE)
																														.addGroup(
																																jPanel2Layout
																																		.createParallelGroup(
																																				Alignment.TRAILING)
																																		.addComponent(
																																				jLabel4)
																																		.addComponent(
																																				jLabel5)
																																		.addComponent(
																																				jLabel6,
																																				GroupLayout.PREFERRED_SIZE,
																																				92,
																																				GroupLayout.PREFERRED_SIZE)))
																										.addComponent(
																												jLabel7,
																												Alignment.TRAILING,
																												GroupLayout.DEFAULT_SIZE,
																												GroupLayout.DEFAULT_SIZE,
																												Short.MAX_VALUE))
																						.addComponent(
																								jLabel8)))
														.addGroup(
																jPanel2Layout
																		.createSequentialGroup()
																		.addContainerGap()
																		.addComponent(
																				jLabel10)))
										.addPreferredGap(
												ComponentPlacement.RELATED)
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																Alignment.LEADING)
														.addGroup(
																jPanel2Layout
																		.createSequentialGroup()
																		.addGroup(
																				jPanel2Layout
																						.createParallelGroup(
																								Alignment.TRAILING)
																						.addComponent(
																								firstNameValidation)
																						.addComponent(
																								lastNameValidation)
																						.addComponent(
																								jTextField2,
																								Alignment.LEADING,
																								GroupLayout.PREFERRED_SIZE,
																								188,
																								GroupLayout.PREFERRED_SIZE))
																		.addGap(157))
														.addGroup(
																jPanel2Layout
																		.createSequentialGroup()
																		.addGap(1)
																		.addGroup(
																				jPanel2Layout
																						.createParallelGroup(
																								Alignment.LEADING)
																						.addComponent(
																								emailIdValidation,
																								GroupLayout.DEFAULT_SIZE,
																								344,
																								Short.MAX_VALUE)
																						.addComponent(
																								passWordValidation,
																								341,
																								341,
																								341)
																						.addComponent(
																								jPasswordField1,
																								GroupLayout.PREFERRED_SIZE,
																								184,
																								GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jPasswordField2,
																								GroupLayout.PREFERRED_SIZE,
																								182,
																								GroupLayout.PREFERRED_SIZE)))
														.addComponent(
																jTextField1,
																GroupLayout.PREFERRED_SIZE,
																188,
																GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jTextField3,
																GroupLayout.PREFERRED_SIZE,
																188,
																GroupLayout.PREFERRED_SIZE)
														.addGroup(
																jPanel2Layout
																		.createSequentialGroup()
																		.addComponent(
																				retypeValidation,
																				GroupLayout.DEFAULT_SIZE,
																				249,
																				Short.MAX_VALUE)
																		.addGap(96))
														.addComponent(
																jTextArea1,
																GroupLayout.PREFERRED_SIZE,
																265,
																GroupLayout.PREFERRED_SIZE))
										.addContainerGap())
						.addGroup(
								jPanel2Layout
										.createSequentialGroup()
										.addContainerGap(168, Short.MAX_VALUE)
										.addComponent(jButton2,
												GroupLayout.PREFERRED_SIZE, 91,
												GroupLayout.PREFERRED_SIZE)
										.addGap(50)
										.addComponent(jButtonRegister,
												GroupLayout.PREFERRED_SIZE, 91,
												GroupLayout.PREFERRED_SIZE)
										.addGap(147)));
		jPanel2Layout
				.setVerticalGroup(jPanel2Layout
						.createParallelGroup(Alignment.LEADING)
						.addGroup(
								jPanel2Layout
										.createSequentialGroup()
										.addGap(19)
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																Alignment.BASELINE)
														.addComponent(jLabel6)
														.addComponent(
																jTextField2,
																GroupLayout.PREFERRED_SIZE,
																GroupLayout.DEFAULT_SIZE,
																GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												ComponentPlacement.RELATED)
										.addComponent(firstNameValidation)
										.addPreferredGap(
												ComponentPlacement.RELATED)
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																Alignment.BASELINE)
														.addComponent(
																jTextField3,
																GroupLayout.PREFERRED_SIZE,
																GroupLayout.DEFAULT_SIZE,
																GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel7))
										.addPreferredGap(
												ComponentPlacement.RELATED)
										.addComponent(lastNameValidation)
										.addPreferredGap(
												ComponentPlacement.RELATED)
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																Alignment.BASELINE)
														.addComponent(jLabel4)
														.addComponent(
																jTextField1,
																GroupLayout.PREFERRED_SIZE,
																GroupLayout.DEFAULT_SIZE,
																GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												ComponentPlacement.RELATED)
										.addComponent(emailIdValidation)
										.addGap(8)
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																Alignment.BASELINE)
														.addComponent(
																jPasswordField1,
																GroupLayout.PREFERRED_SIZE,
																GroupLayout.DEFAULT_SIZE,
																GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel5))
										.addPreferredGap(
												ComponentPlacement.RELATED, 8,
												Short.MAX_VALUE)
										.addComponent(passWordValidation)
										.addPreferredGap(
												ComponentPlacement.RELATED)
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																Alignment.BASELINE)
														.addComponent(
																jPasswordField2,
																GroupLayout.PREFERRED_SIZE,
																GroupLayout.DEFAULT_SIZE,
																GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel8))
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																Alignment.LEADING)
														.addGroup(
																jPanel2Layout
																		.createSequentialGroup()
																		.addGap(13)
																		.addComponent(
																				retypeValidation)
																		.addPreferredGap(
																				ComponentPlacement.RELATED)
																		.addComponent(
																				jTextArea1,
																				GroupLayout.PREFERRED_SIZE,
																				107,
																				GroupLayout.PREFERRED_SIZE))
														.addGroup(
																jPanel2Layout
																		.createSequentialGroup()
																		.addGap(28)
																		.addComponent(
																				jLabel10)))
										.addPreferredGap(
												ComponentPlacement.RELATED, 16,
												Short.MAX_VALUE)
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																Alignment.BASELINE)
														.addComponent(
																jButtonRegister,
																GroupLayout.PREFERRED_SIZE,
																38,
																GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jButton2,
																GroupLayout.PREFERRED_SIZE,
																38,
																GroupLayout.PREFERRED_SIZE))
										.addGap(135)));
		jPanel2.setLayout(jPanel2Layout);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		layout.setHorizontalGroup(layout
				.createParallelGroup(Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGroup(
										layout.createParallelGroup(
												Alignment.TRAILING, false)
												.addComponent(
														jPanel1,
														Alignment.LEADING,
														GroupLayout.DEFAULT_SIZE,
														GroupLayout.DEFAULT_SIZE,
														Short.MAX_VALUE)
												.addComponent(
														jPanel2,
														Alignment.LEADING,
														GroupLayout.DEFAULT_SIZE,
														495, Short.MAX_VALUE))
								.addContainerGap(GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addComponent(jPanel1,
										GroupLayout.PREFERRED_SIZE,
										GroupLayout.DEFAULT_SIZE,
										GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(ComponentPlacement.RELATED)
								.addComponent(jPanel2,
										GroupLayout.DEFAULT_SIZE,
										GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)));
		getContentPane().setLayout(layout);

		pack();
	}// </editor-fold>//GEN-END:initComponents

	


	

	@SuppressWarnings("deprecation")
	private void jButtonRegisterActionPerformed() {

		
		Users user = new Users();
		String pass = jPasswordField1.getText().toString();
		String pass1 = jPasswordField2.getText().toString();
		boolean validationFlag = false;

		boolean emailIDvalidationFlag = validationMethod(emailIdValidation,
				EMAIL_PATTERN, jTextField1, QUERY_EMAIL_ID);
		boolean userNamevalidationFlag = validationMethod(firstNameValidation,
				NAME_PATTERN, jTextField2, QUERY_USER_ID);
		boolean lastNamevalidationFlag = validationMethod(lastNameValidation,
				NAME_PATTERN, jTextField3, StringUtils.EMPTY);

		if (!nameNEmailValidation(jPasswordField1.getText(), PLABEL_PATTERN)) {
			passWordValidation.setText("please min length of 6 ");

		} else {
			passWordValidation.setText("");
			validationFlag = true;

		}

		if (!pass1.equals(pass)) {
			if (validationFlag) {
				validationFlag = false;
			}
			retypeValidation.setText("reenter password");
		} else {
			retypeValidation.setText("");
			validationFlag = true;
		}

		Object[] options = { "OK" };
		if (validationFlag && userNamevalidationFlag && emailIDvalidationFlag
				&& lastNamevalidationFlag) {
			
			String message=ResetPassword.sendMail(jTextField1.getText(),"","Please Wait for Moment for activation Your Account","Thank you for registering with us "+ '\n'+"Please Wait for 30-45 mins for activation of account "+ '\n'+"Team will send u activation mail" + '\n' + '\n' + "");

			if(message.equals("success")){
				user.setDisplayName(jTextField3.getText());
				user.setUserName(jTextField2.getText());
				user.setEmailId(jTextField1.getText());
				user.setPassword(jPasswordField1.getText());
				StoreFileAsJson.storeDataToDB(user);
				int choice = JOptionPane.showOptionDialog(null,
						"Please open  again application to LOGIN", "Message",
						JOptionPane.YES_OPTION, JOptionPane.QUESTION_MESSAGE, null,
						options, options[0]);
				if (choice == JOptionPane.OK_OPTION) {
					System.exit(0);
				}
			}else{
				
				int choice = JOptionPane.showOptionDialog(null,
						"Entered EMailId is not Correct please enter correct one", "Message",
						JOptionPane.YES_OPTION, JOptionPane.QUESTION_MESSAGE, null,
						options, options[0]);
				if (choice == JOptionPane.OK_OPTION) {
					dispose();
				}
			}
			
		}

		// interpret the user's choice

	}// GEN-LAST:event_jButtonRegisterActionPerformed

	private boolean validationMethod(JLabel validationLabel,
			String validationPattern, JTextField textField, String queryId) {
		boolean valueFlag = true;
		if (!nameNEmailValidation(textField.getText(), validationPattern)) {
			LOGGER.info("validationFlag -in second method--"
					+ textField.getText());

			validationLabel.setForeground(Color.RED);
			validationLabel.setText("Please enter correct");
			valueFlag = false;

		} else {
			boolean flag = true;
			if (!queryId.isEmpty()) {
				flag = StoreFileAsJson.checkAlreadyInDB(textField.getText(),
						queryId);
			}

			if (!flag) {
				validationLabel.setText("Already  exist!");
				validationLabel.setForeground(Color.RED);

				valueFlag = false;
			} else {
				validationLabel.setText("");
				validationLabel.setForeground(new Color(204, 204, 204));

			}
		}
		return valueFlag;
	}

	private boolean nameNEmailValidation(String text, String patternToValidate) {
		Matcher matchers;
		Pattern patterns;

		patterns = Pattern.compile(patternToValidate);
		matchers = patterns.matcher(text);

		return matchers.matches();
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String[] args) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed"
		// desc=" Look and feel setting code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase
		 * /tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException | InstantiationException
				| IllegalAccessException
				| javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(RegisterForm.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		Runnable task2=()->new RegisterForm().setVisible(true);
		EventQueue.invokeLater(task2);
	}

	private javax.swing.JPasswordField jPasswordField1;
	private javax.swing.JPasswordField jPasswordField2;

	private javax.swing.JTextField jTextField1;
	private javax.swing.JTextField jTextField2;
	private javax.swing.JTextField jTextField3;
	private JLabel firstNameValidation;
	private JLabel lastNameValidation;
	private JLabel emailIdValidation;
	private JLabel passWordValidation;
	private JLabel retypeValidation;
	private static final String EMAIL_PATTERN = "^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@"
			+ "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$";

	private static final String NAME_PATTERN = "[_A-Za-z-'\\s]+";
	private static final String PLABEL_PATTERN = "^[a-z0-9_-]{6,12}$";
	private static final String QUERY_EMAIL_ID = "from Users where emailId = :code";
	private static final String QUERY_USER_ID = "from Users where userName = :code";

	// End of variables declaration//GEN-END:variables
}
